### PR TITLE
Merge iguanair-lirc into iguanair, some fixes

### PR DESCRIPTION
**Pull request by leamas**
With the packaging hat on it turns out that having the lirc driver in a separate repository is a major headache (it forces me to create, review and maintain a separate package; don't want that). So, I suggest that the lirc-driver is merged into the main repo, but on a separate branch.

This request is against master, but again: the idea is that it should be on a separate branch.

Some packaging fixes added on top of that

### CODE REVIEW

**Comment by jdunn14** [comment]
It's fine with me to put the files in the main repository, but I do have a couple git related questions.
1. For my own information, when you refer to having to maintain another package, what package(s) are you referring to and why does the separate repo cause the problem?
2. I don't follow why this would be a separate branch.  Is the idea that this would be temporary and eventually merged into master?

**Comment by leamas** [comment]
On 14/01/16 02:02, jdunn14 wrote:

> It's fine with me to put the files in the main repository, but I do have
> a couple git related questions.
> 
>  1.
> 
> ```
> For my own information, when you refer to having to maintain another
> package, what package(s) are you referring to and why does the
> separate repo cause the problem?
> ```

I'm referring to the downstream Fedora iguanaIR package. Fedora, like 
most (all?) other distros has a simple rule that each distro package 
corresponds a single "upstream". This means that if lirc-drv-irman would 
live in a separate github repo I would have to create and maintain a new 
Fedora package which is much more work than to just update the igianaIr 
package with a new subpackage.

Subpackages are
fine as long as they are built from the same "upstream" sources.

>  2.
> 
> ```
> I don't follow why this would be a separate branch. Is the idea that
> this would be temporary and eventually merged into master?
> ```

Yes.

Cheers!

--alec

**Comment by IguanaBen** [comment]
Sounds reasonable. I made a new branch (lirc-drv-iguanair) -- do you mind doing a new pull request again that branch? 

Also, before you do the new commits/pull requests, could you take a look at 4a47098 -- looks like a formatting change is making the file look entirely new instead of just changing a few lines. Everything else looks good and we can merge into lirc-drv-iguanair.

**Comment by leamas** [comment]
OK. Closing this in favor of updated #23

**Pull request closed without merging**
